version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(filename)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /mnt/c/Users/satyendra.mishra/Work/mle-training/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /mnt/c/Users/satyendra.mishra/Work/mle-training/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers: [console, info_file_handler, error_file_handler]
    propogate: yes

# loggers:
#     <module>:
#         level: INFO
#         handlers: [console, info_file_handler, error_file_handler]
#         propogate: no

#     <module.x>:
#         level: DEBUG
#         handlers: [info_file_handler, error_file_handler]
#         propogate: yes